os: linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

language: c
compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-six python-pygments graphviz python-lxml

script: make
